languageCode  = "en-us"
title         = "Emelyn Lybarger"
theme         = "roxo"
summarylength = 25
baseURL       = "https://n8behavior.github.io/emelyn-lybarger-website/"
canonifyurls  = true

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Home"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "About"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Blog"
    url     = "blog"
    weight  = 3
  [[menu.nav]]
    name    = "Get in touch"
    url     = "contact"
    weight  = 4

# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = ""
  author = "Emelyn Lybarger"
  # Google Analitycs
  googleAnalitycsID = ""
  # We're using formspree.io for form handling, paste your formspree url below
  formspreeFormUrl  = ""
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/hero-background.jpg"
    heading               = "Mind-Body Learning For Lasting Change"
    tagline               = "LIFE & LEADERSHIP COACHING"
    primary_button        = "Recent Posts"
    primary_button_url    = "blog"
    secondary_button      = "Connect with Us"
    secondary_button_url  = "contact"

  [params.call_to_action]
    enable              = false
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "LETâ€™S WORK TOGETHER"
    primary_button      = "Contact Us"
    primary_button_url  = "contact"
    secondary_button    = "Not Convinced"
    secondary_button_url = "portfolio"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contact Info"
      address = "4374 Dublin Rd.<br>Columbus, OH 43221"
      phone   = "614-499-2815"
      email   = "emelyn@emelynlybarger.com"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "About"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Blog"
          url  = "blog"
        [[params.footer.sitemap.link]]
          name = "Contact"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "Medium"
          url  = "#"
        [[params.footer.social.link]]
          name = "Behance"
          url  = "#"
        [[params.footer.social.link]]
          name = "Dribbble"
          url  = "#"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "#"
      # Footer Service
      [params.footer.service]
        title       = "We help:"
        description = "develop...<br>produce valuable cultural...<br>create..."
